# Generated by Django 2.1.5 on 2019-01-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_place2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place2',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place2',
        ),
    ]
