# Generated by Django 2.1.5 on 2019-01-09 15:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190109_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPlace',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('polls.place',),
            managers=[
                ('second', django.db.models.manager.Manager()),
            ],
        ),
    ]
