# Generated by Django 2.1.5 on 2019-01-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_proxyplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyPlace',
        ),
    ]
