# Generated by Django 2.1.5 on 2019-01-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='L',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
                ('h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t.H')),
            ],
        ),
        migrations.AddField(
            model_name='l',
            name='m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t.M'),
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('v', models.IntegerField(default=0)),
                ('storage', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
                ('a', models.ManyToManyField(to='t.A')),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='b',
            name='s',
            field=models.ManyToManyField(to='t.S'),
        ),
        migrations.CreateModel(
            name='Im',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.ImageField(upload_to='', width_field='w')),
                ('w', models.IntegerField()),
            ],
        ),
    ]
