# Generated by Django 2.1.5 on 2019-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_data_20190127_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='MI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.IntegerField(default=0)),
                ('v2', models.IntegerField(default=0)),
                ('v3', models.IntegerField(default=0)),
            ],
        ),
    ]
